myboot:
  http:
    router:
      auto-init: true
  mongodb:
    clients:
    - name: sync
      primary: true
      uri: mongodb://localhost:27017
      databases:
      - name: test
        id: syncTest
        primary: true
    - name: reactivestreams
      driver: reactivestreams
      uri: mongodb://localhost:27017
      databases:
      - name: test
        id: reactivestreamsTest
  redis:
    lettuce:
      client:
        connections:
        - name: test
          uri: redis://localhost:6379/2
        - name: hello
          uri: redis://localhost:6379/3
          type: pubsub
        pools:
        - name: blocking
          uri: redis://localhost:6379/4
          mode: sync
        - name: noblocking
          uri: redis://localhost:6379/5
          mode: async
        - name: noblockingPlus
          uri: redis://localhost:6379/6
          mode: async-plus
          wrap-connections: false
  aliyun-ons:
    consumers:
    - name: test
      namesrv-addr: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
      group-id: GID_test
      access-key: AccessKey
      secret-key: SecretKey
      consume-thread-nums: 24
