myboot:
  mongodb:
    clients:
    - name: sync
      primary: true
      uri: mongodb://10.7.125.140:27017
      databases:
      - name: test
        id: syncTest
        primary: true
    - name: reactivestreams
      driver: reactivestreams
      uri: mongodb://10.7.125.140:27017
      databases:
      - name: test
        id: reactivestreamsTest
  redis:
    lettuce:
      client:
        connections:
        - name: test
          uri: redis://10.7.125.116:6379/2
        - name: hello
          uri: redis://10.7.125.116:6379/3
          type: pubsub
